version: "3.7"

volumes:
  grafana-storage:


services:
  camera-config:
    build: camera-config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  rtsp:
    build: rtsp
    restart: unless-stopped
    network_mode: host
    ports:
      - 8554:8554
    volumes:
      - ./rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./crop/getcrop.sh:/getcrop.sh
      - ./crop/crop.yml:/crop.yml
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  pygateway:
    build: pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquittoconf
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"

