version: "3.7"

volumes:
  grafana-storage:


services:
  pygateway:
    build: pygateway
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    tty: true
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquittoconf
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"

