version: "3.7"


services:
  config-manager:
    build: services/config-manager
    tty: true
    volumes:
      - ./config:/config
    environment:
      CROP_YML_FILE: "/config/crop.yml"
    restart: unless-stopped
    network_mode: host
  rtsp:
    build: services/rtsp
    restart: unless-stopped
    network_mode: host
    ports:
      - 8554:8554
    volumes:
      - ./services/rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./services/rtsp/scripts:/scripts
      - ./config:/config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  pygateway:
    build: services/pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    restart: unless-stopped
    network_mode: host
  goo:
    build: services/goo
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ${LIGHT_STORES_DIR}:/light-stores
      - /dev:/dev