version: "3.7"

volumes:
  grafana-storage:


services:
  camera-config:
    build: services/camera-config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  config-manager:
    build: services/config-manager
    tty: true
    volumes:
      - ./config:/config
    depends_on:
      - mosquitto
    environment:
      CROP_YML_FILE: "/config/crop.yml"
  rtsp:
    build: services/rtsp
    restart: unless-stopped
    network_mode: host
    ports:
      - 8554:8554
    volumes:
      - ./services/rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml
      - ./services/rtsp/scripts:/scripts
      - ./config:/config
    devices:
      - $TOP_CAM:/dev/top-cam
      - $FRONT_CAM:/dev/front-cam
  pygateway:
    build: services/pygateway
    devices:
      - /dev/ttyACM0
    tty: true
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto:/mosquittoconf
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"

